data streaming2;
set streaming;
avgi=mean(of q_1-q_21);
mini=min (of q_1-q_21);
maxi=max(of q_1-q_21);
array a1 q_1-q_21;
array a2 new_q_1-new_q_21;
do over a2;
if a1>avgi then a2=(a1-avgi)/(maxi-avgi);
if a1<avgi then a2=(a1-avgi)/(avgi-mini);
if a1 =. then a2=0;
end;
label new_q_1="Wide content";
label new_q_2="Convenience";
label new_q_3="Recommendations";
label new_q_4="Customer service";
label new_q_5="Quality";
label new_q_6="Plans";
label new_q_7="Languages";
label new_q_8="Offline watching";
label new_q_9="Cost";
label new_q_10="Longer waiting";
label new_q_11="Parental control";
label new_q_12="Wider content";
label new_q_13="Saving money";
label new_q_14="Other countries";
label new_q_15="Search language";
label new_q_16="Pop-up";
label new_q_17="Malware/viruses";
label new_q_18="Downloading";
label new_q_19="Friends";
label new_q_20="Less waiting";
label new_q_21="No content control";
run;

proc means data=streaming2;
var new_q:;
run;
